[tool.poetry]
name = "barista"
version = "0.1.0"
description = "A Python and Jsonnet Framework for handling Espanso Configurations"
authors = ["Jeppe Klitgaard <hi@jeppe.science>"]
license = "MIT"

[tool.poetry.scripts]
barista = "barista.__main__:cli"

[tool.poetry.dependencies]
python = "^3.9"
jsonnet = "^0.17.0"
PyYAML = "^5.4.1"
click = "^8.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
